import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ShoppingBag, Search, Heart, Menu, X, Star, ArrowRight, Truck, ShieldCheck, Headphones, ChevronRight, Play, Minus, Plus, Trash2, ChevronLeft } from 'lucide-react';
import './style.css';

const MEDIA = {
  video: 'https://videos.pexels.com/video-files/3195394/3195394-hd_1920_1080_25fps.mp4',
  hero: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1400',
};
const products = [
  {id:1,n:'AeroBook Pro 14',cat:'Laptops',price:1299,tag:'New',img:'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1000',desc:'A powerful, lightweight laptop built for work, creativity and everyday performance.'},
  {id:2,n:'V-Phone Ultra',cat:'Smartphones',price:999,tag:'Bestseller',img:'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1000',desc:'A premium smartphone with a brilliant display, fast performance and all-day battery life.'},
  {id:3,n:'Pulse Watch X',cat:'Smart Watches',price:349,tag:'-15%',img:'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1000',desc:'Track your day, workouts and notifications from a refined smart wearable.'},
  {id:4,n:'Sonic Pro Max',cat:'Audio',price:249,tag:'Popular',img:'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=1000',desc:'Immersive wireless audio with rich sound and comfortable all-day listening.'},
  {id:5,n:'NovaCam 4K',cat:'Cameras',price:799,tag:'Pro',img:'https://images.pexels.com/photos/9095/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1000',desc:'Capture sharp 4K moments with a versatile camera designed for creators.'},
  {id:6,n:'GameCore X',cat:'Gaming',price:599,tag:'Hot',img:'https://images.pexels.com/photos/3945654/pexels-photo-3945654.jpeg?auto=compress&cs=tinysrgb&w=1000',desc:'Next-level gaming performance, responsive controls and immersive entertainment.'},
  {id:7,n:'HomeHub Mini',cat:'Smart Home',price:129,tag:'Smart',img:'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1000',desc:'Bring simple connected controls to your home with a compact smart hub.'},
  {id:8,n:'Voltix Buds',cat:'Accessories',price:99,tag:'Value',img:'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1000',desc:'Compact wireless earbuds for calls, music and life on the move.'}
];
const cats=['Smartphones','Laptops','Gaming','Audio','Smart Watches','Smart Home','Cameras','Accessories'];
const navItems=[['Shop','/shop'],['New Arrivals','/new'],['Deals','/deals'],['Support','/support']];
const money=n=>`$${n.toLocaleString()}`;

function go(path){ window.history.pushState({},'',path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({top:0,behavior:'smooth'}); }
function usePath(){const [path,setPath]=useState(window.location.pathname||'/');useEffect(()=>{const f=()=>setPath(window.location.pathname||'/');window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);return path;}
function Link({to,children,className=''}){return <a className={className} href={to} onClick={e=>{if(!to.startsWith('http')){e.preventDefault();go(to)}}}>{children}</a>}

function Header({cartCount,wishCount,search,setSearch}){const [menu,setMenu]=useState(false);return <><div className="top">Free shipping on orders over $100 <span>•</span> Secure checkout <span>•</span> 2-year warranty on selected products</div><header><Link className="logo" to="/"><b>V</b> VOLTIX</Link><nav>{navItems.map(([x,to])=><Link key={to} to={to}>{x}</Link>)}</nav><div className="actions"><div className="search"><Search size={18}/><input placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)}/></div><Link to="/wishlist" className="iconBtn" aria-label="Wishlist"><Heart size={20}/><i>{wishCount}</i></Link><Link to="/cart" className="iconBtn" aria-label="Cart"><ShoppingBag size={20}/><i>{cartCount}</i></Link><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<div className="mobileNav">{navItems.map(([x,to])=><Link key={to} to={to} onClick={()=>setMenu(false)}>{x}</Link>)}<Link to="/wishlist">Wishlist</Link><Link to="/cart">Cart</Link></div>}</>}

function ProductCard({p,wish,setWish,add}){const wished=wish.includes(p.id);return <article className="product"><Link to={`/product/${p.id}`} className="productImg"><span>{p.tag}</span><button onClick={e=>{e.preventDefault();setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}}><Heart size={18} fill={wished?'currentColor':'none'}/></button><img src={p.img} onError={e=>{e.currentTarget.src=MEDIA.hero}}/></Link><div className="productInfo"><small>{p.cat}</small><Link to={`/product/${p.id}`}><h3>{p.n}</h3></Link><div className="rating"><Star size={14} fill="currentColor"/> 4.9 <span>(128)</span></div><div className="buy"><strong>{money(p.price)}</strong><button onClick={()=>add(p)}>Add to cart</button></div></div></article>}

function Home({wish,setWish,add}){return <><section className="hero"><video className="heroVideo" autoPlay muted loop playsInline poster={MEDIA.hero}><source src={MEDIA.video} type="video/mp4"/></video><div className="videoShade"/><div className="heroText"><span className="eyebrow">NEXT-GEN TECHNOLOGY · 2026</span><h1>Future technology,<br/><em>delivered today.</em></h1><p>Discover premium electronics engineered for how you live, work, create, and play.</p><div className="buttons"><Link className="primary" to="/shop">Shop now <ArrowRight size={17}/></Link><Link className="ghost" to="/new">Explore new arrivals</Link></div><div className="trust"><span><ShieldCheck/> Authentic products</span><span><Truck/> Fast delivery</span></div></div><div className="heroProduct"><div className="playBadge"><Play size={16} fill="currentColor"/> LIVE PRODUCT SHOWCASE</div><img src={MEDIA.hero} onError={e=>e.currentTarget.style.display='none'}/><div className="floatCard"><small>FEATURED</small><strong>V-Phone Ultra</strong><span>From $999</span></div></div></section><section className="section"><div className="sectionHead"><div><span className="eyebrow">SHOP BY CATEGORY</span><h2>Find your next device.</h2></div><Link to="/shop">View all <ArrowRight size={16}/></Link></div><div className="categories">{cats.map((c,i)=><Link key={c} to={`/category/${encodeURIComponent(c)}`} className="cat"><div className="catIcon">{['◈','▣','⌁','◉','◌','⌂','◎','＋'][i]}</div><strong>{c}</strong><ChevronRight size={15}/></Link>)}</div></section><section className="section dark"><div className="featureGrid"><div><span className="eyebrow">THE VOLTIX DIFFERENCE</span><h2>Technology that<br/><em>moves with you.</em></h2><p>Every product is selected for useful innovation, dependable quality and a better everyday experience.</p><Link className="lightBtn" to="/about">Discover Voltix <ArrowRight size={17}/></Link></div><div className="featureImage"><img src="https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1400"/><div className="spec"><b>Designed for tomorrow.</b><span>Power · Precision · Possibility</span></div></div></div></section><section className="section"><div className="sectionHead"><div><span className="eyebrow">CURATED FOR YOU</span><h2>Featured products.</h2></div><Link to="/shop">View all <ArrowRight size={16}/></Link></div><div className="products">{products.slice(0,6).map(p=><ProductCard key={p.id} p={p} wish={wish} setWish={setWish} add={add}/>)}</div></section><Perks/><Newsletter/></>}

function Perks(){return <section className="perks">{[[Truck,'Fast & free delivery','On orders over $100'],[ShieldCheck,'Secure payments','Protected checkout'],[Headphones,'Expert support',"We're here 24/7"],[Heart,'30-day returns','Shop with confidence']].map(([I,b,s])=><div key={b}><I/><b>{b}</b><span>{s}</span></div>)}</section>}
function Newsletter(){return <section className="newsletter"><span className="eyebrow">STAY IN THE LOOP</span><h2>Be first to know what's next.</h2><p>New launches, exclusive offers, and tech worth talking about.</p><div><input placeholder="Your email address"/><button>Subscribe <ArrowRight size={16}/></button></div></section>}

function Listing({title,eyebrow,items,wish,setWish,add}){return <main className="page"><div className="pageHero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>Explore Voltix products with clear details, useful filters and direct paths to every product.</p></div><div className="section"><div className="products">{items.length?items.map(p=><ProductCard key={p.id} p={p} wish={wish} setWish={setWish} add={add}/>):<div className="empty"><h2>No products found</h2><Link className="primary" to="/shop">Back to shop</Link></div>}</div></div></main>}

function ProductPage({product,wish,setWish,add}){const [qty,setQty]=useState(1);if(!product)return <NotFound/>;return <main className="page"><div className="breadcrumbs"><Link to="/shop">Shop</Link><ChevronRight size={14}/><span>{product.n}</span></div><section className="productDetail"><div className="detailImage"><img src={product.img} onError={e=>e.currentTarget.src=MEDIA.hero}/><span>{product.tag}</span></div><div className="detailInfo"><small>{product.cat}</small><h1>{product.n}</h1><div className="rating"><Star size={16} fill="currentColor"/> 4.9 <span>(128 verified reviews)</span></div><strong className="detailPrice">{money(product.price)}</strong><p>{product.desc}</p><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={15}/></button><b>{qty}</b><button onClick={()=>setQty(qty+1)}><Plus size={15}/></button></div><button className="primary wide" onClick={()=>{for(let i=0;i<qty;i++)add(product)}}>Add {qty} to cart <ShoppingBag size={17}/></button><button className="save" onClick={()=>setWish(w=>w.includes(product.id)?w.filter(x=>x!==product.id):[...w,product.id])}><Heart size={17} fill={wish.includes(product.id)?'currentColor':'none'}/> {wish.includes(product.id)?'Saved to wishlist':'Add to wishlist'}</button><div className="detailBullets"><span>✓ Authentic Voltix product</span><span>✓ Fast delivery available</span><span>✓ 30-day returns</span></div></div></section><section className="section related"><div className="sectionHead"><h2>You may also like</h2><Link to="/shop">Shop all <ArrowRight size={16}/></Link></div><div className="products">{products.filter(p=>p.cat===product.cat&&p.id!==product.id).slice(0,3).concat(products.filter(p=>p.id!==product.id).slice(0,3)).slice(0,3).map(p=><ProductCard key={p.id} p={p} wish={wish} setWish={setWish} add={add}/>)}</div></section></main>}

function CartPage({cart,setCart}){const total=cart.reduce((s,p)=>s+p.price,0);return <main className="page"><div className="pageHero"><span className="eyebrow">YOUR BAG</span><h1>Shopping cart</h1><p>Your cart is independent from the homepage and ready for checkout.</p></div><div className="cartPage section">{cart.length?<><div className="cartList">{cart.map((p,i)=><div className="cartRow" key={`${p.id}-${i}`}><img src={p.img}/><div><small>{p.cat}</small><h3>{p.n}</h3><strong>{money(p.price)}</strong></div><button onClick={()=>setCart(c=>c.filter((_,x)=>x!==i))}><Trash2 size={17}/></button></div>)}</div><aside className="summary"><h2>Order summary</h2><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Shipping</span><b>{total>=100?'Free': '$15'}</b></div><div className="total"><span>Total</span><b>{money(total+(total>=100?0:15))}</b></div><button className="primary wide">Secure checkout <ArrowRight size={17}/></button><Link className="continue" to="/shop"><ChevronLeft size={15}/> Continue shopping</Link></aside></>:<div className="empty"><ShoppingBag size={45}/><h2>Your cart is empty</h2><p>Add products from the shop to see them here.</p><Link className="primary" to="/shop">Start shopping</Link></div>}</div></main>}

function WishlistPage({wish,setWish,add}){const items=products.filter(p=>wish.includes(p.id));return <Listing title="Your wishlist" eyebrow="SAVED FOR LATER" items={items} wish={wish} setWish={setWish} add={add}/>}
function Support(){return <main className="page"><div className="pageHero"><span className="eyebrow">SUPPORT</span><h1>How can we help?</h1><p>Get product guidance, delivery help, returns information or reach the Voltix team.</p></div><section className="supportGrid section">{[['Order help','Track an order, delivery or return.'],['Product support','Get setup and product guidance.'],['Warranty','Learn about selected-product coverage.'],['Contact us','Talk with our support team.']].map(([t,d])=><Link className="supportCard" to="/contact" key={t}><Headphones/><h3>{t}</h3><p>{d}</p><ArrowRight/></Link>)}</section></main>}
function SimplePage({type}){const data={about:['ABOUT VOLTIX','Technology for modern life.','Voltix is a premium electronics storefront focused on useful technology, transparent product information and a smooth shopping experience.'],contact:['CONTACT','We are here to help.','Email support@voltix.example or use the support center to get help with an order or product.'],deals:['DEALS','More technology. Better value.','Discover selected products and limited offers across the Voltix collection.'],new:['NEW ARRIVALS','Meet what is next.','Explore the latest additions to the Voltix collection.']}[type];return <main className="page"><div className="pageHero"><span className="eyebrow">{data[0]}</span><h1>{data[1]}</h1><p>{data[2]}</p><Link className="primary" to={type==='deals'?'/deals':type==='new'?'/new':'/shop'}>{type==='about'?'Explore the collection':'Browse products'} <ArrowRight size={17}/></Link></div>{type==='about'&&<Perks/>}</main>}
function NotFound(){return <main className="page"><div className="pageHero"><span className="eyebrow">404</span><h1>Page not found.</h1><p>This page is independent and can be reached directly, but the address you entered does not exist.</p><Link className="primary" to="/">Back home</Link></div></main>}

function App(){const path=usePath();const [cart,setCart]=useState([]),[wish,setWish]=useState([]),[search,setSearch]=useState('');const add=p=>setCart(c=>[...c,p]);const searchItems=useMemo(()=>products.filter(p=>(p.n+' '+p.cat).toLowerCase().includes(search.toLowerCase())),[search]);let content;if(path==='/')content=<Home wish={wish} setWish={setWish} add={add}/>;else if(path==='/shop')content=<Listing title="Shop all products" eyebrow="THE COLLECTION" items={search?searchItems:products} wish={wish} setWish={setWish} add={add}/>;else if(path==='/new')content=<Listing title="New arrivals" eyebrow="JUST LANDED" items={products.slice(0,4)} wish={wish} setWish={setWish} add={add}/>;else if(path==='/deals')content=<Listing title="Deals & offers" eyebrow="LIMITED VALUE" items={products.filter(p=>p.tag==='-15%'||p.tag==='Value'||p.tag==='Popular')} wish={wish} setWish={setWish} add={add}/>;else if(path==='/wishlist')content=<WishlistPage wish={wish} setWish={setWish} add={add}/>;else if(path==='/cart')content=<CartPage cart={cart} setCart={setCart}/>;else if(path==='/support')content=<Support/>;else if(path==='/about')content=<SimplePage type="about"/>;else if(path==='/contact')content=<SimplePage type="contact"/>;else if(path.startsWith('/category/')){const cat=decodeURIComponent(path.split('/').pop());content=<Listing title={cat} eyebrow="CATEGORY" items={products.filter(p=>p.cat===cat)} wish={wish} setWish={setWish} add={add}/>;}else if(path.startsWith('/product/'))content=<ProductPage product={products.find(p=>p.id===Number(path.split('/').pop()))} wish={wish} setWish={setWish} add={add}/>;else content=<NotFound/>;return <><Header cartCount={cart.length} wishCount={wish.length} search={search} setSearch={setSearch}/>{content}<footer><div><Link className="logo" to="/"><b>V</b> VOLTIX</Link><p>Premium technology for modern life.</p></div><div><strong>Shop</strong><Link to="/shop">All products</Link><Link to="/new">New arrivals</Link><Link to="/deals">Deals</Link><Link to="/wishlist">Wishlist</Link></div><div><strong>Help</strong><Link to="/support">Support</Link><Link to="/contact">Contact</Link><Link to="/cart">Shipping & cart</Link></div><div><strong>Company</strong><Link to="/about">About us</Link><Link to="/shop">Journal</Link><Link to="/contact">Careers</Link></div><div className="copy">© 2026 Voltix Electronics. All rights reserved. <span>Photos and videos provided by Pexels where used.</span></div></footer>{cart.length>0&&<Link className="cartPill" to="/cart">{cart.length} item{cart.length>1?'s':''} in cart <ShoppingBag size={17}/></Link>}</>}
createRoot(document.getElementById('root')).render(<App/>);
